import { Course, CourseLevel } from './types';

export const MOCK_COURSES: Course[] = [
  // COMPUTER SCIENCE COURSES
  {
    id: 'cs1',
    title: 'Full Stack Web Developer',
    shortDescription: 'Master the MERN stack and build production-ready applications with internship support.',
    longDescription: 'This comprehensive bootcamp takes you from zero to hero in full-stack web development. You will learn modern JavaScript, React 18, Node.js, Express, and MongoDB. The course includes real-world projects, resume building, and guaranteed internship opportunities upon completion.',
    category: 'Computer Science',
    price: 4999,
    originalPrice: 12999,
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=450&fit=crop',
    rating: 4.7,
    reviewsCount: 2298,
    level: CourseLevel.Intermediate,
    duration: '12 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i1',
      name: 'Priya Sharma',
      bio: 'Senior Full Stack Developer with 10+ years of experience.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=6366f1&color=fff',
      rating: 4.9
    },
    skills: ['React', 'Node.js', 'MongoDB', 'TypeScript', 'AWS'],
    features: ['Internship Included', 'Placement Assistance', 'Live Projects'],
    syllabus: [
      { title: 'Frontend Foundations', duration: '2 Weeks', lessons: [{ title: 'HTML5 & CSS3 Mastery', type: 'video' }, { title: 'JS ES6+ Deep Dive', type: 'video' }] },
      { title: 'React Ecosystem', duration: '4 Weeks', lessons: [{ title: 'Hooks & Context API', type: 'video' }, { title: 'Redux Toolkit', type: 'assignment' }] },
      { title: 'Backend Engineering', duration: '4 Weeks', lessons: [{ title: 'RESTful APIs with Express', type: 'video' }, { title: 'Database Design', type: 'quiz' }] }
    ],
    reviews: [],
    bestseller: true
  },
  {
    id: 'cs2',
    title: 'Artificial Intelligence',
    shortDescription: 'Learn AI fundamentals, machine learning, deep learning, and neural networks.',
    longDescription: 'Comprehensive AI course covering machine learning algorithms, neural networks, computer vision, and natural language processing with hands-on projects.',
    category: 'Computer Science',
    price: 6999,
    originalPrice: 15999,
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 2340,
    level: CourseLevel.Advanced,
    duration: '16 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i2',
      name: 'Dr. Rajesh Kumar',
      bio: 'AI Research Scientist with PhD in Machine Learning.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Rajesh+Kumar&background=8b5cf6&color=fff',
      rating: 4.9
    },
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Neural Networks', 'NLP'],
    features: ['Internship Included', 'Research Projects', 'Industry Mentorship'],
    syllabus: [],
    reviews: [],
    bestseller: true
  },
  {
    id: 'cs3',
    title: 'Data Analytics',
    shortDescription: 'Master data analysis, visualization, and business intelligence tools.',
    longDescription: 'Learn to analyze complex datasets, create insightful visualizations, and make data-driven decisions using Python, SQL, and BI tools.',
    category: 'Computer Science',
    price: 4499,
    originalPrice: 10999,
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
    rating: 4.7,
    reviewsCount: 2690,
    level: CourseLevel.Intermediate,
    duration: '12 Weeks',
    lastUpdated: 'November 2024',
    instructor: {
      id: 'i3',
      name: 'Anita Desai',
      bio: 'Data Analytics Expert with 8+ years in Business Intelligence.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Anita+Desai&background=ec4899&color=fff',
      rating: 4.8
    },
    skills: ['Python', 'SQL', 'Power BI', 'Tableau', 'Excel'],
    features: ['Job Assistance', 'Real-world Projects', 'Certification'],
    syllabus: [],
    reviews: []
  },
  {
    id: 'cs4',
    title: 'Cloud Computing',
    shortDescription: 'Master AWS, Azure, and Google Cloud platforms with hands-on labs.',
    longDescription: 'Comprehensive cloud computing course covering major cloud platforms, DevOps practices, and cloud architecture design.',
    category: 'Computer Science',
    price: 5499,
    originalPrice: 12999,
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 2156,
    level: CourseLevel.Advanced,
    duration: '14 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i4',
      name: 'Vikram Singh',
      bio: 'AWS Certified Solutions Architect and Cloud Consultant.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Vikram+Singh&background=3b82f6&color=fff',
      rating: 4.9
    },
    skills: ['AWS', 'Azure', 'Docker', 'Kubernetes', 'Terraform'],
    features: ['Certification Prep', 'Cloud Labs', 'Placement Support'],
    syllabus: [],
    reviews: [],
    bestseller: true
  },
  {
    id: 'cs5',
    title: 'Data Science',
    shortDescription: 'Learn Python, statistics, machine learning, and data visualization.',
    longDescription: 'Complete data science bootcamp covering Python programming, statistical analysis, machine learning algorithms, and real-world data projects.',
    category: 'Computer Science',
    price: 5999,
    originalPrice: 14999,
    thumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 2699,
    level: CourseLevel.Intermediate,
    duration: '16 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i5',
      name: 'Dr. Meera Patel',
      bio: 'PhD in Statistics, ex-Google Data Scientist.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Meera+Patel&background=10b981&color=fff',
      rating: 4.9
    },
    skills: ['Python', 'Pandas', 'Scikit-Learn', 'SQL', 'TensorFlow'],
    features: ['Job Guarantee Program', '1-on-1 Mentorship', 'Portfolio Building'],
    syllabus: [],
    reviews: [],
    bestseller: true
  },
  {
    id: 'cs6',
    title: 'Cyber Security',
    shortDescription: 'Learn ethical hacking, network security, and cybersecurity best practices.',
    longDescription: 'Comprehensive cybersecurity course covering penetration testing, network security, cryptography, and security operations.',
    category: 'Computer Science',
    price: 6499,
    originalPrice: 15999,
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 1856,
    level: CourseLevel.Advanced,
    duration: '14 Weeks',
    lastUpdated: 'November 2024',
    instructor: {
      id: 'i6',
      name: 'Arjun Reddy',
      bio: 'Certified Ethical Hacker with 12+ years in InfoSec.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Arjun+Reddy&background=ef4444&color=fff',
      rating: 4.9
    },
    skills: ['Ethical Hacking', 'Network Security', 'Cryptography', 'Penetration Testing'],
    features: ['Certification Prep', 'Live Hacking Labs', 'Job Placement'],
    syllabus: [],
    reviews: []
  },

  // MANAGEMENT COURSES
  {
    id: 'mg1',
    title: 'Business Analytics',
    shortDescription: 'Master business intelligence, data-driven decision making, and analytics tools.',
    longDescription: 'Learn to leverage data for strategic business decisions using advanced analytics tools and methodologies.',
    category: 'Management',
    price: 3999,
    originalPrice: 9999,
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
    rating: 4.7,
    reviewsCount: 2102,
    level: CourseLevel.Intermediate,
    duration: '10 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i7',
      name: 'Kavita Sharma',
      bio: 'MBA from IIM, Business Analytics Consultant.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Kavita+Sharma&background=f59e0b&color=fff',
      rating: 4.8
    },
    skills: ['Business Intelligence', 'Excel', 'Power BI', 'SQL', 'Statistics'],
    features: ['Case Studies', 'Industry Projects', 'Placement Support'],
    syllabus: [],
    reviews: []
  },
  {
    id: 'mg2',
    title: 'Finance',
    shortDescription: 'Learn financial analysis, investment strategies, and corporate finance.',
    longDescription: 'Comprehensive finance course covering financial modeling, investment analysis, and corporate financial management.',
    category: 'Management',
    price: 4499,
    originalPrice: 11999,
    thumbnail: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 2076,
    level: CourseLevel.Intermediate,
    duration: '12 Weeks',
    lastUpdated: 'November 2024',
    instructor: {
      id: 'i8',
      name: 'Rahul Mehta',
      bio: 'CFA Charterholder, ex-Investment Banker.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Rahul+Mehta&background=14b8a6&color=fff',
      rating: 4.9
    },
    skills: ['Financial Modeling', 'Investment Analysis', 'Excel', 'Valuation'],
    features: ['CFA Prep', 'Live Trading Sessions', 'Job Assistance'],
    syllabus: [],
    reviews: [],
    bestseller: true
  },
  {
    id: 'mg3',
    title: 'Human Resource',
    shortDescription: 'Master HR management, talent acquisition, and organizational development.',
    longDescription: 'Complete HR management course covering recruitment, employee relations, performance management, and HR analytics.',
    category: 'Management',
    price: 3499,
    originalPrice: 8999,
    thumbnail: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&h=450&fit=crop',
    rating: 4.9,
    reviewsCount: 2087,
    level: CourseLevel.Beginner,
    duration: '10 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i9',
      name: 'Sneha Kapoor',
      bio: 'SHRM Certified, 15+ years in HR Leadership.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Sneha+Kapoor&background=a855f7&color=fff',
      rating: 4.9
    },
    skills: ['Recruitment', 'Employee Relations', 'HR Analytics', 'Performance Management'],
    features: ['SHRM Certification Prep', 'Case Studies', 'Internship'],
    syllabus: [],
    reviews: []
  },
  {
    id: 'mg4',
    title: 'Digital Marketing',
    shortDescription: 'Master SEO, social media marketing, content marketing, and paid advertising.',
    longDescription: 'Comprehensive digital marketing course covering all aspects of online marketing including SEO, SEM, social media, and analytics.',
    category: 'Management',
    price: 3999,
    originalPrice: 9999,
    thumbnail: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?w=800&h=450&fit=crop',
    rating: 4.7,
    reviewsCount: 2257,
    level: CourseLevel.Beginner,
    duration: '10 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i10',
      name: 'Amit Verma',
      bio: 'Google Certified Digital Marketer, Agency Owner.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Amit+Verma&background=06b6d4&color=fff',
      rating: 4.8
    },
    skills: ['SEO', 'Google Ads', 'Social Media Marketing', 'Content Marketing', 'Analytics'],
    features: ['Google Certification', 'Live Campaigns', 'Freelancing Guide'],
    syllabus: [],
    reviews: [],
    bestseller: true
  },
  {
    id: 'mg5',
    title: 'Stock Marketing',
    shortDescription: 'Learn stock trading, technical analysis, and investment strategies.',
    longDescription: 'Master the stock market with comprehensive training in technical analysis, fundamental analysis, and trading strategies.',
    category: 'Management',
    price: 4999,
    originalPrice: 12999,
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 980,
    level: CourseLevel.Intermediate,
    duration: '8 Weeks',
    lastUpdated: 'November 2024',
    instructor: {
      id: 'i11',
      name: 'Suresh Raina',
      bio: 'Professional Trader with 10+ years experience.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Suresh+Raina&background=84cc16&color=fff',
      rating: 4.9
    },
    skills: ['Technical Analysis', 'Fundamental Analysis', 'Trading Strategies', 'Risk Management'],
    features: ['Live Trading Sessions', 'Market Analysis', 'Trading Tools'],
    syllabus: [],
    reviews: []
  },
  {
    id: 'mg6',
    title: 'Supply Chain Management',
    shortDescription: 'Master logistics, procurement, inventory management, and supply chain optimization.',
    longDescription: 'Comprehensive supply chain management course covering end-to-end supply chain operations and optimization strategies.',
    category: 'Management',
    price: 3999,
    originalPrice: 10999,
    thumbnail: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=450&fit=crop',
    rating: 4.7,
    reviewsCount: 1069,
    level: CourseLevel.Intermediate,
    duration: '10 Weeks',
    lastUpdated: 'November 2024',
    instructor: {
      id: 'i12',
      name: 'Deepak Gupta',
      bio: 'Supply Chain Director with 12+ years in Logistics.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Deepak+Gupta&background=f97316&color=fff',
      rating: 4.8
    },
    skills: ['Logistics', 'Procurement', 'Inventory Management', 'SAP', 'Lean Six Sigma'],
    features: ['SAP Training', 'Industry Projects', 'Placement Support'],
    syllabus: [],
    reviews: []
  },

  // ELECTRONICS/ELECTRICAL COURSES
  {
    id: 'ee1',
    title: 'Embedded Systems',
    shortDescription: 'Learn microcontrollers, IoT, and embedded programming with hands-on projects.',
    longDescription: 'Master embedded systems development with Arduino, Raspberry Pi, and professional embedded C programming.',
    category: 'Electronics/Electrical',
    price: 4999,
    originalPrice: 11999,
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop',
    rating: 4.7,
    reviewsCount: 1543,
    level: CourseLevel.Intermediate,
    duration: '12 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i13',
      name: 'Rahul Srivastava',
      bio: 'Embedded Systems Engineer with 10+ years in IoT.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Rahul+Srivastava&background=6366f1&color=fff',
      rating: 4.8
    },
    skills: ['Arduino', 'Raspberry Pi', 'Embedded C', 'IoT', 'RTOS'],
    features: ['Hardware Kits Included', 'Live Projects', 'Industry Mentorship'],
    syllabus: [],
    reviews: []
  },

  // MEDICAL COURSES
  {
    id: 'md1',
    title: 'Psychology',
    shortDescription: 'Explore human behavior, mental health, and psychological theories.',
    longDescription: 'Comprehensive psychology course covering clinical psychology, counseling techniques, and mental health assessment.',
    category: 'Medical',
    price: 3499,
    originalPrice: 8999,
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 1876,
    level: CourseLevel.Beginner,
    duration: '12 Weeks',
    lastUpdated: 'November 2024',
    instructor: {
      id: 'i14',
      name: 'Nishitha Jha',
      bio: 'Clinical Psychologist with M.Phil in Psychology.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Nishitha+Jha&background=ec4899&color=fff',
      rating: 4.9
    },
    skills: ['Clinical Psychology', 'Counseling', 'Mental Health', 'Psychotherapy'],
    features: ['Certification', 'Case Studies', 'Practical Training'],
    syllabus: [],
    reviews: []
  },

  // ADDITIONAL COURSES
  {
    id: 'ad1',
    title: 'Graphics Design',
    shortDescription: 'Master Adobe Creative Suite, UI/UX design, and visual communication.',
    longDescription: 'Complete graphics design course covering Photoshop, Illustrator, InDesign, and modern design principles.',
    category: 'Design',
    price: 2999,
    originalPrice: 7999,
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&h=450&fit=crop',
    rating: 4.9,
    reviewsCount: 2669,
    level: CourseLevel.Beginner,
    duration: '10 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i15',
      name: 'Pooja Malhotra',
      bio: 'Senior Graphic Designer with 8+ years experience.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Pooja+Malhotra&background=8b5cf6&color=fff',
      rating: 4.9
    },
    skills: ['Photoshop', 'Illustrator', 'InDesign', 'Figma', 'UI/UX'],
    features: ['Portfolio Building', 'Freelancing Guide', 'Adobe Certification'],
    syllabus: [],
    reviews: [],
    bestseller: true
  },
  {
    id: 'ad2',
    title: 'Fintech',
    shortDescription: 'Learn blockchain, cryptocurrency, digital payments, and financial technology.',
    longDescription: 'Explore the intersection of finance and technology with courses on blockchain, DeFi, and digital banking.',
    category: 'Finance',
    price: 5499,
    originalPrice: 13999,
    thumbnail: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 1250,
    level: CourseLevel.Advanced,
    duration: '12 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i16',
      name: 'Karan Malhotra',
      bio: 'Blockchain Expert and Fintech Consultant.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Karan+Malhotra&background=10b981&color=fff',
      rating: 4.9
    },
    skills: ['Blockchain', 'Cryptocurrency', 'Smart Contracts', 'DeFi', 'Digital Payments'],
    features: ['Blockchain Projects', 'Industry Insights', 'Certification'],
    syllabus: [],
    reviews: []
  },
  {
    id: 'ad3',
    title: 'Mobile App Development',
    shortDescription: 'Build iOS and Android apps using React Native and Flutter.',
    longDescription: 'Complete mobile app development course covering cross-platform development with React Native and Flutter.',
    category: 'Development',
    price: 4999,
    originalPrice: 12999,
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=450&fit=crop',
    rating: 4.8,
    reviewsCount: 1987,
    level: CourseLevel.Intermediate,
    duration: '14 Weeks',
    lastUpdated: 'December 2024',
    instructor: {
      id: 'i17',
      name: 'Deepak Kumar',
      bio: 'Mobile App Developer with 50+ published apps.',
      avatarUrl: 'https://ui-avatars.com/api/?name=Deepak+Kumar&background=3b82f6&color=fff',
      rating: 4.9
    },
    skills: ['React Native', 'Flutter', 'iOS', 'Android', 'Firebase'],
    features: ['App Publishing Guide', 'Live Projects', 'Placement Support'],
    syllabus: [],
    reviews: [],
    bestseller: true
  }
];

export const CATEGORIES = [
  "Computer Science",
  "Management",
  "Electronics/Electrical",
  "Medical",
  "Design",
  "Finance",
  "Development"
];
